### ISSUE TITLE
It hide the averages/Les moyennes sont cachées

### ISSUE THREAD

**Issue by Tom-GARNIER** [Max1Truc/ecoledirecte-plus-plus#1]
Hello,
First, your extension is awesome.
But I found a problem there: on the "evaluation" page, I no longer see the average column. I can see my averages very well on the "average" page, but not on the "evaluation" =.
Is this normal?

Bonjour,
Premièrement, votre extension est géniale.
Mais j'y ai trouvé un problème: sur la page "évaluation", je ne vois plus la colone moyenne. Je vois très bien mes moyennes sur la page "moyenne", mais pas sur celle "évaluation" =.
Est-ce normal?

**Comment by Tom-GARNIER** [comment]
@Max1Truc

**Comment by Max1Truc** [comment]
Bonjour,

C'est peut-être normal, ou peut-être pas...

Je m'explique:

Certains établissements, en plus de les cacher, ne calculent tout simplement pas certaines des ou toutes les moyennes, ce qui empêche cet outil de fonctionner.

Je pense que c'est aussi le cas de ton établissement.

Je n'ai cependant plus de compte EcoleDirecte et je ne peux donc plus le vérifier.

Si tu t'y connais un peu en développement web, ou quelqu'un d'autre qui passerait par ici, voici quelques étapes pour le vérifier par toi-même:
- Désinstalle ou désactive l'extension temporairement, le temps de vérifier
- Rends-toi sur la page de connexion d'EcoleDirecte
- Fais un clic droit n'importe-où sur la page, et sélectionne `Inspecter`
- Clique sur l'onglet "Réseau"
- Clique sur "Filtrer des URL", et entre "notes"
- Maintenant que tout est prêt, laisse le menu de développement ouvert, connecte-toi, et rends-toi sur la page des notes
- Tu devrais voir qu'une ou plusieurs lignes sont apparues dans le menu de développement
- Pour chaque ligne (elles ne correspondent peut-être pas toutes aux bonnes données, essaie les toutes s'il y en a plusieurs), tu peux regarder le résultat de la requête en cliquant dessus et en sélectionnant l'onglet "Réponse" à droite.
- Tu as alors la réponse du site EcoleDirecte, qui contient parfois des informations intéressantes sur tes notes qui ne sont pas affichées normalement

Je t'invite à explorer ces informations. Les paramètres d'affichages des notes sont dans "data" puis "parametrage". Si tu arrives jusque-là, ce serait super si tu pouvais m'envoyer un copier-coller ou une capture d’écran de ce que contient "parametrage" Avant de l'envoyer, je t'invite aussi à vérifier qu'il n'y a pas de données personnelles dedans, comme le nom de ton établissement par exemple.

Merci d'avoir pris la peine de lire ce pavé !

Edit:
Oh et merci ! Ça fait plaisir de savoir que quelqu'un utilise mon extension. J'apprécie aussi beaucoup que tu aies ouvert une `issue` et décrit ton problème, c'est très rare. Merci !

**Comment by Tom-GARNIER** [comment]
Bonjour,
Je vous tiens au courant d'une possible solution, avez-vous prévu de mettre cette solution disponible sur google chrome?

**Comment by Tom-GARNIER** [comment]
J'ai trouvé aussi d'autre possible erreurs pour l'extension:

- [ ] Les moyennes ne sont plus affichées
- [ ] (je suppose un problème de mon établissement ou par rapport au semestre) Problème sur l'affichage du rang pour les matières (dernier, alors que je pense être plus haut dans le classement 😅 )
- [ ] Les composants numérique me retourne une erreur 403

Suggestions: 

- [ ] Fonctionnalité pour google chrome
- [ ] Option d'un recalcul de toute les moyennes automatiquement, sans envoyer une requête à EcoleDirecte
- [ ] (petit plaisir personnel) Voir son rang par rapport à une note (je ne suis pas sûr que cela est possible)

Problème me concernant:

- [ ] Je ne parvient pas à modifier l'extension:
J'arrive à récupérer le code, mais pas à le remettre, cela me signale que l'extension est corrompue

**Comment by Max1Truc** [comment]
> J'ai trouvé aussi d'autre possible erreurs pour l'extension:
> - [ ]  Les moyennes ne sont plus affichées

Ok, j'attends d'avoir une screenshot, ne pouvant plus tester par moi-même.

> - [ ]  (je suppose un problème de mon établissement ou par rapport au semestre) Problème sur l'affichage du rang pour les matières (dernier, alors que je pense être plus haut dans le classement :sweat_smile: )

En effet, c'est probablement dû à votre établissement, mais cela peut aussi être la faute d'une mauvaise modification des paramètres par l'extension.

> - [ ]  Les composants numérique me retourne une erreur 403

Qu'entendez-vous par "les composants numérique" ?

> Suggestions: 
> - [ ]  Fonctionnalité pour google chrome

Ce n'est pas prévu, notamment parce qu'il faut payer pour publier une extension sur le Chrome Webstore.
Cependant, l'extension étant disponible sous une licence open-source, n'importe qui est libre de publier cette extension soi-même sur le magasin d'extensions de Google Chrome, en respectant les termes de la licence ( cf le fichier `LICENSE` ).

> - [ ]  Option d'un recalcul de toute les moyennes automatiquement, sans envoyer une requête à EcoleDirecte

Le re-calcul des moyennes sans passer par EcoleDirecte n'est pas prévu, mais il serait possible de calculer les moyennes quand elles sont demandées à EcoleDirecte, et que le site ne les donne pas. J'aurais cependant besoin d'un compte pour pouvoir développer cette fonctionnalité efficacement, que je n'ai pas. Il faudra donc attendre que quelqu'un code cette fonctionnalité et m'envoie ses modifications (cf https://docs.github.com/en/pull-requests/collaborating-with-pull-requests, il est aussi possible de m'envoyer les modifications en .zip dans une issue si c'est trop compliqué).

> - [ ]  (petit plaisir personnel) Voir son rang par rapport à une note (je ne suis pas sûr que cela est possible)

Si vous parlez du rang pour chaque note, je ne pense pas que cela soit possible malheureusement, à ma connaissance le rang par note n'est pas donné par le site et je ne vois pas comment le calculer.

> Problème me concernant:
> - [ ]  Je ne parvient pas à modifier l'extension: J'arrive à récupérer le code, mais pas à le remettre, cela me signale que l'extension est corrompue

Qu'entendez-vous par le remettre ?

**Comment by Scramjet-0** [comment]
@Max1Truc C'est dommage que tu ne puisse plus developer cette extension car tu n'as pas ecole directe... Perso j'aimerais (car je ne trouve pas normal que les profs aient des infos que nous n'avons pas...) mais je ne connas pas les langage web (quelques bases en Java) il n'y a pas moyen que je te fasse un sorte de copier de la page pour que tu puisse l'inspecter ? Je pourrais toujours de preter mon compte maiiiis ouai je te connais pas donc...

**Comment by asyncrom** [comment]
Sinon en rapport avec ton message précedent (réponse à Tom) j'ai trouvé ca mais je ne peux pas passer la valeur sur true
![image](https://user-images.githubusercontent.com/64070810/142754946-ec4dbc1a-a82e-4b02-9f19-9c8d227d2040.png)

**Comment by Tom-GARNIER** [comment]
@Scramjet-0 Où as tu trouvé cela?

**Comment by Tom-GARNIER** [comment]
> Qu'entendez-vous par le remettre ?

Et bien, je vais dans le dossier des extensions de firefox, je d-zip le dossier, mais je n'arrive pas à le re-zipper et le remettre dans les extensions firefox

**Comment by asyncrom** [comment]
> @Scramjet-0 Où as tu trouvé cela?

J'ai fait exactement ce qu'il a dit plus haut

**Comment by Tom-GARNIER** [comment]
> J'ai fait exactement ce qu'il a dit plus haut

Je viens de trouver 😄

**Comment by Tom-GARNIER** [comment]
> Sinon en rapport avec ton message précedent (réponse à Tom) j'ai trouvé ca mais je ne peux pas passer la valeur sur true ![image](https://user-images.githubusercontent.com/64070810/142754946-ec4dbc1a-a82e-4b02-9f19-9c8d227d2040.png)

J'ai toutes les options sur `true`

**Comment by Tom-GARNIER** [comment]
![image](https://user-images.githubusercontent.com/69351379/142755119-437b9595-3603-44f3-af60-3147a9bea535.png)

**Comment by asyncrom** [comment]
> 

Alors tu devrais pouvoir voir ta moyenne et autre xD Qu'il est mal foutu ce site

**Comment by Tom-GARNIER** [comment]
Je les voies très bien, mais que dans l'onglet `moyennes`, pas dans l'onglet `évaluations` comme avant

**Comment by asyncrom** [comment]
@Max1Truc Il doit y avoir plein d'autres choses qui sont envoyées mais blocké

**Comment by Tom-GARNIER** [comment]
J'ai fais une comparaison des donnée de la réponse avec l'extension activée, ou non, et j'obtient exactement les même informations (voir screen)

**Comment by asyncrom** [comment]
Oui c'est vrai

**Comment by Tom-GARNIER** [comment]
Je ne comprends pas, en explorant l'api, je trouve bien les moyennes des chaque matières, pourquoi ne sont telles pas affichées?

**Comment by Tom-GARNIER** [comment]
Bon, j'ai trouvé, les moyennes ne sont pas dans la partie `note` de l'api...

**Comment by asyncrom** [comment]
> Bon, j'ai trouvé, les moyennes ne sont pas dans la partie `note` de l'api...

?

**Comment by Tom-GARNIER** [comment]
Voilà un schéma de l'api:
```json
{
   "data":{
      "periodes":[],
      "notes":[],
      "parametrage":{
      },
      "LSUN":{}}}
```
L'extension va chercher les notes dans la partie `notes` mais ne va pas dans celle de `périodes` pour  la page évaluation

C'est la seule possibilité pourquoi on ne voit pas nos moyennes

**Comment by Max1Truc** [comment]
@Scramjet-0 
> il n'y a pas moyen que je te fasse un sorte de copier de la page pour que tu puisse l'inspecter ?

Ce serait inutile la page ne contient pas les infos en elles-même.

> Je pourrais toujours de preter mon compte maiiiis ouai je te connais pas donc...

Je ne compte pas utiliser le compte de quelqu'un d'autre de toute manière.

> J'ai trouvé ca mais je ne peux pas passer la valeur sur true

Merci pour la capture d'écran, je vais étudier ça.

@Tom-GARNIER 

> Et bien, je vais dans le dossier des extensions de firefox, je d-zip le dossier, mais je n'arrive pas à le re-zipper et le remettre dans les extensions firefox

Ce site explique comment tester une extension (cf la colonne code dans le tableau): https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Firefox_workflow_overview (cf "about:debugging" et à "select any file inside the extension" il faut sélectionner le fichier "manifest.json")

> J'ai toutes les options sur true

Merci aussi pour la capture d'écran.

> J'ai fais une comparaison des donnée de la réponse avec l'extension activée, ou non, et j'obtient exactement les même informations (voir screen)

Firefox affiche les vraies données envoyées par EcoleDirecte, avant qu'elles ne soient modifiées par l'extension. Quand on étudie les réponses d'EcoleDirecte, il vaut tout de même mieux désinstaller l'extension pour être sûr...

> L'extension va chercher les notes dans la partie notes mais ne va pas dans celle de périodes pour la page évaluation

L'extension ne touche pas aux notes, seulement aux paramètres pour les afficher, EcoleDirecte se charge tout seul du reste.

**Comment by Tom-GARNIER** [comment]
> L'extension ne touche pas aux notes, seulement aux paramètres pour les afficher, EcoleDirecte se charge tout seul du reste.

Donc, cela signifie qu'il y a un paramètre que l'extension désactive.

> Firefox affiche les vraies données envoyées par EcoleDirecte, avant qu'elles ne soient modifiées par l'extension. Quand on étudie les réponses d'EcoleDirecte, il vaut tout de même mieux désinstaller l'extension pour être sûr...

J'ai été voir sur google chrome, où  il n'y a pas l'extension

> Je ne compte pas utiliser le compte de quelqu'un d'autre de toute manière.

Il faudrait comme ProNote, un compte de test pour l'api. Malheureusement, EcoleDirecte ne ma jamais répondu à ma demande de faire des compte de test, pour admin, prof et élèves.

**Comment by Scramjet-0** [comment]
@Max1Truc Juste une question indiscret e : ou est ce que tu as appris les language web ?

**Comment by Tom-GARNIER** [comment]
Perso, j'ai appris en essayant et en recherchant sur internet.
J'utilise l'api EcoleDirecte par python, comme je maitrise bien ce language

**Comment by asyncrom** [comment]
> Perso, j'ai appris en essayant et en recherchant sur internet.
> J'utilise l'api EcoleDirecte par python, comme je maitrise bien ce language

Les languages web ont l´air intéressants,  moi ce qui compte c´est qu´il y ai des projets a faire avec, avec Java on peut faire des plugins pour Minecraft donc ça me motive

**Comment by Tom-GARNIER** [comment]
On peut faire un site avec du java?

**Comment by asyncrom** [comment]
> On peut faire un site avec du java?

Non mais du backend je crois, et vu que c´est orienté objet des jeux video

**Comment by Tom-GARNIER** [comment]
Ok
Là, il faudrait vraiment trouver une solution à ce problème là

**Comment by asyncrom** [comment]
> Ok
> Là, il faudrait vraiment trouver une solution à ce problème là

Mais, quel problème ?

**Comment by Tom-GARNIER** [comment]
Les moyennes ne sont plus affichées, le titre de l'issue

**Comment by asyncrom** [comment]
> Les moyennes ne sont plus affichées, le titre de l'issue

Tu as encore ce problème,  dans l´onglet année tu na pas moyenne ? Comme la dit Max c'est que ton lycée ne calcul pas la moyenne

**Comment by Tom-GARNIER** [comment]
Sans l'extension elle sont affichées dans l'onglet `évaluations`, avec l'extension, il faut que j'ailles dans l'onglet `moyennes` pour les voir, c'est embêtant, c'est pour ça que je dis que c'est un problème, il faudrait qu'elle soient affichées dans la page `évaluations` même avec l'extension

**Comment by Max1Truc** [comment]
> Donc, cela signifie qu'il y a un paramètre que l'extension désactive.

En effet.

> Il faudrait comme ProNote, un compte de test pour l'api. Malheureusement, EcoleDirecte ne ma jamais répondu à ma demande de faire des compte de test, pour admin, prof et élèves.

Ce serait super en effet, mais je n'y crois pas trop...

> @Max1Truc Juste une question indiscrete : ou est ce que tu as appris les language web ?

Bonne question, je ne sais pas précisément mais je sais que la [MDN](https://developer.mozilla.org/fr/docs/Learn) et [openclassrooms](https://openclassrooms.com/fr/) m'ont été utiles.

> Sans l'extension elle sont affichées dans l'onglet `évaluations`, avec l'extension, il faut que j'ailles dans l'onglet `moyennes` pour les voir, c'est embêtant, c'est pour ça que je dis que c'est un problème, il faudrait qu'elle soient affichées dans la page `évaluations` même avec l'extension

Ok, je regarde les captures d'écran quand je peux.

**Comment by Max1Truc** [comment]
Je vous invite à tester les modifications que j'ai faites sur GitHub (non publiées sur Mozilla Add-ons)

**Comment by asyncrom** [comment]
> Je vous invite à tester les modifications que j'ai faites sur GitHub (non publiées sur Mozilla Add-ons)

Je fais ça des que je peux, sur linux: je prends le zip et je le met qq part ?

**Comment by Max1Truc** [comment]
Il faut extraire le zip et sélectionner le fichier "manifest.json" comme expliqué dans l'un des messages précédents.

**Comment by Tom-GARNIER** [comment]
@Max1Truc Je n'arrive pas à l'importer dans Firefox, que faut t'il faire avec le fichier `manifest.json` ?

**Comment by Max1Truc** [comment]
> > Et bien, je vais dans le dossier des extensions de firefox, je d-zip le dossier, mais je n'arrive pas à le re-zipper et le remettre dans les extensions firefox
> 
> Ce site explique comment tester une extension (cf la colonne "code" dans le tableau): https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Firefox_workflow_overview (cf "about:debugging" et à "select any file inside the extension" il faut sélectionner le fichier "manifest.json")

**Comment by Tom-GARNIER** [comment]
Merci
Cela ne change rien du tout

**Comment by Tom-GARNIER** [comment]
![image](https://user-images.githubusercontent.com/69351379/142771368-073e9eef-8133-48e4-9e49-e75f3f92e040.png)

**Comment by Max1Truc** [comment]
Est-ce que cette capture d'écran contient toutes les données de "parametrage" ?

Edit: Un copié-collé sera plus efficace qu'une capture d'écran.

**Comment by Tom-GARNIER** [comment]
non, c'est trop court, mais dans tout les cas, je ne voit toujours pas les moyennes
et cela n'a rien changé

**Comment by Max1Truc** [comment]
Un copié-collé de toutes les données de paramétrage me serait utile en fait, peu importe si l'extension les modifie.

**Comment by Tom-GARNIER** [comment]
```json
{
	"parametrage": {
		"couleurEval1": "#ff0000",
		"couleurEval2": "#ffc000",
		"couleurEval3": "#0070c0",
		"couleurEval4": "#00b050",
		"libelleEval1": "",
		"libelleEval2": "",
		"libelleEval3": "",
		"libelleEval4": "",
		"affichageMoyenne": true,
		"affichageMoyenneDevoir": true,
		"affichagePositionMatiere": false,
		"affichageNote": true,
		"affichageCompetence": true,
		"affichageEvaluationsComposantes": false,
		"affichageGraphiquesComposantes": true,
		"modeCalculGraphiquesComposantes": "eval",
		"affichageCompNum": false,
		"libelleEvalCompNum1": "",
		"libelleEvalCompNum2": "",
		"libelleEvalCompNum3": "",
		"affichageAppreciation": true,
		"appreciationsProf": true,
		"appreciationProfPrinc": true,
		"affichageMention": true,
		"affichageAppreciationCE": true,
		"affichageAppreciationVS": true,
		"affichageAppreciationCN": false,
		"affichageAppreciationClasse": true,
		"affichageAppreciationPeriodeCloturee": true,
		"moyenneUniquementPeriodeCloture": false,
		"moyennePeriodeReleve": true,
		"moyennePeriodeAnnuelle": true,
		"moyennePeriodeHorsP": true,
		"moyenneEleveDansNotes": true,
		"moyenneEleve": true,
		"moyenneEleveDansMoyenne": true,
		"moyenneGenerale": true,
		"moyenneCoefMatiere": false,
		"moyenneClasse": true,
		"moyenneMin": true,
		"moyenneMax": true,
		"moyenneRang": false,
		"moyenneSur": 20,
		"moyenneGraphique": false,
		"moyennesSimulation": false,
		"coefficientNote": true,
		"colonneCoefficientMatiere": true,
		"noteGrasSousMoyenne": true,
		"noteGrasAudessusMoyenne": false,
		"libelleDevoir": true,
		"dateDevoir": true,
		"typeDevoir": true,
		"noteUniquementPeriodeCloture": false,
		"notePeriodeReleve": false,
		"notePeriodeAnnuelle": true,
		"notePeriodeHorsP": false,
		"libellesAppreciations": [
			"Appréciation générale"
		],
		"appreciationsParametrage": [
			{
				"code": "APP1",
				"id": 1,
				"nbMaxCaractere": 500,
				"libelle": "Appréciation générale"
			}
		]
	}
}
```

**Comment by Tom-GARNIER** [comment]
(j'ai caché les tokens personnels)

**Comment by Max1Truc** [comment]
Les libelles ne sont pas des tokens à ma connaissance mais je n'en aurais pas besoin de toute manière.

Merci !

**Comment by asyncrom** [comment]
> Les libelles ne sont pas des tokens à ma connaissance mais je n'en aurais pas besoin de toute manière.
> 
> Merci !

Elle est sensé changer quoi la nouvelle version ?

**Comment by asyncrom** [comment]
J´ai essayer de blocker manuellement l´URL que tu block avec l'extension et la page noté ne se charge pas... tu block d´une manière spécifique ?  @Max1Truc

**Comment by Max1Truc** [comment]
> Elle est sensé changer quoi la nouvelle version ?

Elle était censée ne changer que les parametres booléens et pas les libellés ou autres. Le problème aurait pu être la modification de paramètres qui n'auraient pas du l'être.

> J´ai essayer de blocker manuellement l´URL que tu block avec l'extension et la page noté ne se charge pas... tu block d´une manière spécifique ? @Max1Truc

L'extension ne bloque pas d'URL, elle modifie la réponse de l'URL qui permet d'accéder aux notes...

**Comment by Max1Truc** [comment]
Re à tous,

Je n'arrive pas vraiment à isoler le paramètre qui fait tout planter.

Tout ce que je sais c'est que c'est l'un de ceux-là: `affichageAppreciationCN affichageCompNum affichageEvaluationsComposantes affichagePositionMatiere moyenneCoefMatiere moyenneGraphique moyenneRang moyennesSimulation noteGrasAudessusMoyenne notePeriodeHorsP notePeriodeReleve`.

La solution la plus logique (mais légèrement fastidieuse) serait de tester différentes configurations pour isoler ce paramètre.

Je vais avoir besoin qu'au moins un testeur me réponde à chaque fois. J'entends par testeur toute personne qui rencontre le même bug que @Tom-GARNIER.

Je compte donc envoyer différentes versions de l'extension dans cette issue. A chaque fois j'attendrai le retour d'un testeur. Si les moyennes s'affichent dans la page évaluations, j'attends un retour positif ("Ça fonctionne" ou une réaction avec un emoji :+1:  à mon message), sinon j'attends un retour négatif ("Ça ne fonctionne pas" ou une réaction avec un emoji :-1: )

J'envoie la première "version test" sous peu.

EDIT: Pour ceux qui s'y connaissent, je vais utiliser une "binary search"

**Comment by Max1Truc** [comment]
Merci d'essayer le code d'ici: https://github.com/Max1Truc/ecoledirecte-plus-plus/tree/try-fix-issue-1

Tuto (adapté de [extensionworkshop.com](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/)) :

- désinstallez la version normale de l'extension
- téléchargez le fichier zip contenant le code: https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip
- extrayez le contenu du fichier zip dans un nouveau dossier.
- ouvrez Firefox
- entrez "about:debugging" dans la barre d'URL
- cliquez sur "Ce Firefox"
- cliquez sur "Charger un module complémentaire temporaire…"
- naviguez jusqu'au dossier de l'extension, et sélectionnez le fichier `manifest.json`

L'extension de test restera installée jusqu'à ce que vous la supprimiez ou que vous redémarriez Firefox.

**Comment by Tom-GARNIER** [comment]
@Max1Truc 
J'ai testé la dernière version, cela ne change rien

**Comment by Max1Truc** [comment]
@Tom-GARNIER Le bug est toujours présent ?

**Comment by Tom-GARNIER** [comment]
oui

**Comment by Tom-GARNIER** [comment]
et les valeurs dans la réponse n'ont pas changé

(désolé pour l'orthographe)

**Comment by Max1Truc** [comment]
Les valeurs de la réponse changent mais Firefox n'affiche pas les changements

**Comment by Max1Truc** [comment]
J'envoie une autre version sous peu

**Comment by Tom-GARNIER** [comment]
ok

**Comment by Max1Truc** [comment]
https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip

**Comment by Max1Truc** [comment]
@Tom-GARNIER

**Comment by Tom-GARNIER** [comment]
@Max1Truc 
C'est bon je vois les moyennes, mais y'a certain composants que je ne voit plus:

- Graphiques
- Composantes

**Comment by Tom-GARNIER** [comment]
+ le rang, je ne le voit plus

**Comment by Tom-GARNIER** [comment]
mais j'ai les moyennes
ainsi que l'onglet des composants numériques qui ne marche pas

**Comment by Max1Truc** [comment]
Seules les moyennes m'intéressent ^^

Il reste encore deux essais et on sera fixés.

**Comment by Tom-GARNIER** [comment]
ok, bah elles sont de nouveau présente

**Comment by Max1Truc** [comment]
https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip

**Comment by Tom-GARNIER** [comment]
Oula
J'ai ni la colonne des moyennes, ni des coef, ni les pages de graphiques et de composantes

Pour faire plus court: j'ai plus rien

**Comment by Max1Truc** [comment]
Ok, dernier essai: https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip

**Comment by Tom-GARNIER** [comment]
Les autres onglet sont revenue, mais pas les colonnes des coefficients et des moyennes sur la page évaluation

**Comment by Max1Truc** [comment]
C'est donc l'un de ces paramètres: `affichageEvaluationsComposantes` `affichagePositionMatiere`.

**Comment by Max1Truc** [comment]
Je vais essayer `affichageEvaluationsComposantes`

**Comment by Tom-GARNIER** [comment]
ok

**Comment by Max1Truc** [comment]
https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip

**Comment by Tom-GARNIER** [comment]
C'est pas bon:
pas de colonne des moyennes
pas d'onglet composante

**Comment by Max1Truc** [comment]
https://github.com/Max1Truc/ecoledirecte-plus-plus/archive/refs/heads/try-fix-issue-1.zip

**Comment by asyncrom** [comment]
J´essai des que je peux

**Comment by Tom-GARNIER** [comment]
@Max1Truc C'est bon!!!!

**Comment by Tom-GARNIER** [comment]
J'ai bien la colonne des moyennes et tous les onglets
est-ce possible de voir une note qu'un prof à voulu nous cacher? 😄

**Comment by Max1Truc** [comment]
> @Max1Truc C'est bon!!!!

Parfait je publierai la correction du bug quand je pourrai.

**Comment by Max1Truc** [comment]
> J'ai bien la colonne des moyennes et tous les onglets
> est-ce possible de voir une note qu'un prof à voulu nous cacher? 😄 

Je ne comprends pas vraiment, normalement tout est affiché.

Ah et merci d'ouvrir une autre issue pour ce problème étant donné que ce n'est pas le même problème que celui du post original.

**Comment by Tom-GARNIER** [comment]
Non, ce n'est pas un problème, juste une petite question
Pouvez-vous mettre à jour l'extension sur firefox?

**Comment by Max1Truc** [comment]
> Non, ce n'est pas un problème, juste une petite question

Dans ce cas je n'ai pas compris la question 🤷

> Pouvez-vous mettre à jour l'extension sur firefox?

Je vais bientôt la mettre à jour oui ^^

**Comment by Tom-GARNIER** [comment]
> Dans ce cas je n'ai pas compris la question 🤷

Les profs ont la possibilité de cacher nos notes, pour pas que l'on les vois à l'avance.
Je demande si c'est possible de contourner ça? 😅

**Comment by Max1Truc** [comment]
Si l'extension ne le permet pas déjà, c'est soit impossible, soit beaucoup trop difficile.

**Comment by Tom-GARNIER** [comment]
ok, je vais demander à mon prof alors...

**Comment by Tom-GARNIER** [comment]
Problème résolu, je ferme cette issue

**Comment by Max1Truc** [comment]
@Tom-GARNIER La mise à jour est en ligne, l'extension sera automatiquement mise à jour sous 24h.

Vous pouvez aussi forcer la mise à jour tout de suite.

**Comment by Tom-GARNIER** [comment]
Est-ce que je peux faire une autre demande concernant les moyennes ici, ou il faut faire une autre issue?

**Comment by Max1Truc** [comment]
C'est beaucoup plus simple pour moi dans une autre issue... mais comme tu veux.

**Comment by Tom-GARNIER** [comment]
@Max1Truc 
Bonjour,
Depuis la mise à jour d'école directe, l'extension ne fonctionne plus (changement de l'adresse des notes)

**Comment by Max1Truc** [comment]
@Tom-GARNIER Merci de créer une nouvelle issue, c'est plus simple pour s'organiser.

Le contenu peut être le même que le dernier message...

**Comment by asyncrom** [comment]
@Max1Truc L'extension marche très bien

**Comment by Scramjet-0** [comment]
Why did you delete the repo @Max1Truc !!!!!!
