### ISSUE TITLE
L'extension ne marche plus

### ISSUE THREAD

**Issue by Tom-GARNIER** [Max1Truc/ecoledirecte-plus-plus#2]
Bonjour,
Depuis la mise à jour d'école directe, l'extension ne fonctionne plus surement du à un changement de l'adresse des notes

**Comment by Tom-GARNIER** [comment]
@Max1Truc

**Comment by Max1Truc** [comment]
Désolé du temps de réponse mais je ne peux pas débuguer ce problème.

Je n'ai pas de compte EcoleDirecte, et les autres codes que j'ai trouvé ne mentionnent pas de changement d'URL pour les notes.

*EDIT:*
Si quelqu'un veut bien m'aider... 
Voici un mini tuto, adapté de l'issue #1.

Si tu t'y connais un peu en développement web, ou quelqu'un d'autre qui passerait par ici, voici quelques étapes pour m'aider:

- Désinstalle ou désactive l'extension (tu pourras la réactiver plus tard)
- Rends-toi sur la page de connexion d'EcoleDirecte
- Fais un clic droit n'importe-où sur la page, et sélectionne Inspecter
- Clique sur l'onglet "Réseau"
- Maintenant que tout est prêt, laisse le menu de développement ouvert, connecte-toi sur EcoleDirecte, et rends-toi sur la page des notes
- Tu devrais voir que beaucoup lignes sont apparues dans le menu de développement
- Essaie plusieurs lignes, en commençant par la dernière, tu peux regarder le résultat de la requête en cliquant dessus et en sélectionnant l'onglet "Réponse" à droite.
- Tu as alors la réponse du site EcoleDirecte, qui contient parfois des informations intéressantes sur tes notes qui ne sont pas affichées normalement

Je t'invite à explorer ces informations. Si rien n'a changé, les paramètres d'affichages des notes sont dans "data" puis "parametrage". Si tu arrives jusque-là, ce serait super si tu pouvais m'envoyer un copier-coller ou une capture d’écran de ce que contient "parametrage" Avant de l'envoyer, je t'invite aussi à vérifier qu'il n'y a pas de données personnelles dedans, comme le nom de ton établissement par exemple. Si tu ne pense rien trouver, n'hésite quand même pas à m'envoyer une capture d'écran des lignes, et des réponses pour au moins les 2 dernières lignes. Encore une fois, vérifie s'il n'y a pas des informations personnelles que tu ne veux pas dévoiler.

**Comment by Tom-GARNIER** [comment]
Bonjour,
Je ne comprend pas très bien ce qu'il faut faire
En observant les données, je remarque que l'url d'api pour les notes est désormais `https://api.ecoledirecte.com/v3/eleves/<id>/notes.awp?verbe=get&v=1.8.8`

Voici la réponse de la requête pour l'url si dessus
```json
{
	"parametrage": {
		"couleurEval1": "#ff0000",
		"couleurEval2": "#ffc000",
		"couleurEval3": "#0070c0",
		"couleurEval4": "#00b050",
		"libelleEval1": je cache...,
		"libelleEval2": je cache...,
		"libelleEval3": je cache...,
		"libelleEval4": je cache...,
		"affichageMoyenne": true,
		"affichageMoyenneDevoir": true,
		"affichagePositionMatiere": false,
		"affichageNote": true,
		"affichageCompetence": true,
		"affichageEvaluationsComposantes": false,
		"affichageGraphiquesComposantes": true,
		"modeCalculGraphiquesComposantes": "eval",
		"affichageCompNum": false,
		"libelleEvalCompNum1": je cache...,
		"libelleEvalCompNum2": je cache...,
		"libelleEvalCompNum3": je cache...,
		"affichageAppreciation": true,
		"appreciationsProf": true,
		"appreciationProfPrinc": true,
		"affichageMention": true,
		"affichageAppreciationCE": true,
		"affichageAppreciationVS": true,
		"affichageAppreciationCN": false,
		"affichageAppreciationClasse": true,
		"affichageAppreciationPeriodeCloturee": true,
		"moyenneUniquementPeriodeCloture": false,
		"moyennePeriodeReleve": true,
		"moyennePeriodeAnnuelle": true,
		"moyennePeriodeHorsP": true,
		"moyenneEleveDansNotes": true,
		"moyenneEleve": true,
		"moyenneEleveDansMoyenne": true,
		"moyenneGenerale": true,
		"moyenneCoefMatiere": false,
		"moyenneClasse": true,
		"moyenneMin": true,
		"moyenneMax": true,
		"moyenneRang": false,
		"moyenneSur": 20,
		"moyenneGraphique": false,
		"moyennesSimulation": false,
		"coefficientNote": true,
		"colonneCoefficientMatiere": true,
		"noteGrasSousMoyenne": true,
		"noteGrasAudessusMoyenne": false,
		"libelleDevoir": true,
		"dateDevoir": true,
		"typeDevoir": true,
		"noteUniquementPeriodeCloture": false,
		"notePeriodeReleve": false,
		"notePeriodeAnnuelle": true,
		"notePeriodeHorsP": false,
		"libellesAppreciations": [
			"Appréciation générale"
		],
		"appreciationsParametrage": [
			{
				"code": "APP1",
				"id": 1,
				"nbMaxCaractere": 600,
				"libelle": "Appréciation générale"
			}
		]
	}
}
``` 

Je ne sais pas si cela est important, mais une adresse ip d'école directe est apparue : `152.228.241.66`

Cordialement

**Comment by Max1Truc** [comment]
Bonjour, ça paraît super !
Il suffit peut-être d'un petit changement dans le code !
Je regarde ça.

Cordialement

**Comment by Tom-GARNIER** [comment]
Merci

**Comment by Max1Truc** [comment]
Serait-il possible de tester cette version de l'extension ?

Merci d'avance ^^


[EcoleDirecte-plus-plus.zip](https://github.com/Max1Truc/ecoledirecte-plus-plus/files/7803494/EcoleDirecte-plus-plus.zip)

**Comment by Max1Truc** [comment]
Note: utiliser ce lien pour charger l'extension: about:debugging#/runtime/this-firefox
Et cliquer sur "Charger un module complémentaire temporaire"

**Comment by Tom-GARNIER** [comment]
@Max1Truc 
Merci, c'est de retour

**Comment by Max1Truc** [comment]
Je n'ai pas encore publié la correction...

Donc ça marche bel et bien ?

**Comment by Tom-GARNIER** [comment]
oui

**Comment by Max1Truc** [comment]
Merci !

**Comment by Max1Truc** [comment]
C'est envoyé ^^

**Comment by Tom-GARNIER** [comment]
Merci
