### ISSUE TITLE
Erreur lorsque j'essaye d'acceder a "composante"

### ISSUE THREAD

**Issue by floconacs** [Max1Truc/ecoledirecte-plus-plus#6]
Bonjour lorsque j'essaye d'acceder a la catégorie composante j'ai une erreur 403 "accès non autorisé" qui s'ouvre. 
serait il possible de contourner cette erreur ? si oui merci de m'indiquer comment.
cordialement,
![image](https://user-images.githubusercontent.com/96012547/177016042-a590f853-2c2b-4df1-91d8-6d92984db30a.png)

**Comment by floconacs** [comment]
@Max1Truc

**Comment by Max1Truc** [comment]
Bonjour,

Tout d'abord, j'apprécie que vous ayez pris le temps de rapporter ce problème.

Il semble que l'extension affiche tout ce qu'elle peut, même des liens qui ne sont pas censés être visibles.

Pour la catégorie composante, vous voyez le lien même si vous n'êtes pas censé(e) y aller, et malheureusement EcoleDirecte vérifie si vous devriez être là ou pas. L'accès vous est ainsi refusé.

Je ne pense donc pas être en mesure de corriger ce problème.

Cordialement,

**Comment by floconacs** [comment]
Bonjour, donc vous pensez que même avec une requête à l'api ou quelque chose d'autre permettant de dire a l'api qu'il me donne les autorisation n'est pas possible ?

**Comment by Max1Truc** [comment]
C'est peut-être possible, mais pour l'instant il me semble surtout que l'api regarde juste l'utilisateur connecté, et en déduit que l'accès est interdit. Il ne devrait pas être possible de contourner ça.

Il est possible que je me trompe mais je ne peux pas vérifier ça par moi-même.

En suivant à peu près le tuto suivant et en cherchant un peu il devrait être possible de m'aider.
https://github.com/Max1Truc/ecoledirecte-plus-plus/issues/2#issuecomment-1003759782

Si aucune requete ne retourne le code 403 une solution est peut-être envisageable. Si une erreur 403 s'affiche dans les requêtes il est très probable que non.

**Comment by floconacs** [comment]
Voila j'ai fais ce que vous m'avez dis de faire depuis le lien de redirection. Il y a bien effectivement une requete 403 qui est faite.
![image](https://user-images.githubusercontent.com/96012547/177163172-e9dbf92f-7a84-4adf-a1dc-b7d7f39944c6.png)
Je vous laisse regarder de vous meme.

**Comment by floconacs** [comment]
Je viens de re regarder, Mozilla m'informe qu'il n' y a aucun parametre pour cette requete et j'ai bien sur une réponse en HTML.

**Comment by Max1Truc** [comment]
Ah, cette requête affiche une page 403 mais le résultat est 200, ce qui signifie "aucun problème".

Y a-t-il une requête qui affiche 403 au lieu de 200 tout à gauche ?

**Comment by Max1Truc** [comment]
PS: pensez à activer l'option "Persist logs"
(Ce site peut aider : https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/toolbar/index.html)

**Comment by floconacs** [comment]
Donc, lorsque je raffraichie la page qui est censé m'amener au niveau des composantes (celle ou est donc marqué erreur 403) au niveau des requetes aucune requete n'affiche 403, il y a 204 mais c'est tout... 
Faudrait il faire une requete à l'API pour lui demander de nous octroyer le droit exceptionnelement ? ou juste de nous dire les valeurs de cette pages composante ?

**Comment by floconacs** [comment]
ou alors faudrait il tout simplement essayer de retirer la requete ou la chose qui regarde les droits de chaques compte ?

**Comment by Max1Truc** [comment]
Il est finalement possible que le serveur ne vérifie pas les droits...

Rechercher les requêtes contenant "api" pourrait aider.

Je ré-ouvre l'issue.

**Comment by floconacs** [comment]
Très bien.
Donc si le serveur ne vérifie pas les droits, quelle requête pourrait aider à contourner cette page d'erreur 403 ? J'ai beau chercher sur internet, je ne sais pas (sachant que je ne dev pas en js...)

**Comment by floconacs** [comment]
Si vous avez un Discord ajoutez moi Flocon V2#3501 il sera plus simple pour nous de communiquer.

**Comment by Max1Truc** [comment]
Après vérification par Discord avec @floconacs, le serveur vérifie bien l'accès et n'envoie qu'un message d'erreurs.
