### ISSUE TITLE
Problème avec les graphiques

### ISSUE THREAD

**Issue by Tom-GARNIER** [Max1Truc/ecoledirecte-plus-plus#9]
Bonjour,
Lorsque je me rends sur la page "Graphique" de l'onglet "Notes" j'ai une erreur qui m'affiche "Accès non autorisé"
J'ai fouillé un peu, et je suis parvenu à accéder à la page. Mais la dernière section ne parvient pas à s'afficher.
Savez-vous comment faire ?
Je sais qu'au début ce n'était disponible que pour les familles, mais en regardant un compte famille je n'ai plus l'option non plus.
Merci

**Comment by Max1Truc** [comment]
Cela signifie que l'école a désactivé l'accès au graphique au lieu d'uniquement le cacher.
